name: DeskTopDiaries
favicon: null
layout_spectrum: 0.31206
typography_spectrum: 0.4535093817394227
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9615404393989593
  lightness: 0.5574175259098411
  saturation: 0.2507951776497066
  rhythmicContrast: 0.9593846313655376
purpose: []
